name: XLSX to TSV Conversion for BU

on:
  push:
    paths:
      - 'data/bulk/templates/'

jobs:
  convert_to_tsv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with your desired Python version

      - name: Install dependencies
        run: pip install openpyxl

      - name: Convert XLSX to TSV
        run: |
          python data/bulk/functions/split_bu_template.py "C:/Rprojects/eamena-arches-dev/data/bulk/templates/doc"

      - name: Commit and push TSV file
        run: |
          git config user.name "zoometh"
          git config user.email "thomashuet7@gmail.com"
          git add data/bulk/templates/doc/
          git commit -m "Convert XLSX to TSV bulkpload"
          git push

