name: XLSX to TSV Conversion mds

on:
  push:
    paths:
      - 'dbs/database.eamena/data/reference_data/mds/mds-template.xlsx'

jobs:
  convert_to_tsv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with your desired Python version

      - name: Install dependencies
        run: pip install openpyxl

      - name: Convert XLSX to TSV
        run: |
          python dbs/database.eamena/data/reference_data/mds/convert_xlsx_to_tsv.py dbs/database.eamena/data/reference_data/mds/mds-template.xlsx dev/data_quality/mds-template-readonly.tsv

      - name: Commit and push TSV file
        run: |
          git config user.name "zoometh"
          git config user.email "thomashuet7@gmail.com"
          git add dbs/database.eamena/data/reference_data/mds/mds-template-readonly.tsv
          git commit -m "Convert XLSX to TSV mds"
          git push

